// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Entry } from 'contentful'

export interface BlogPostFields {
  /** Title */
  title: string

  /** Slug */
  slug: string

  /** Body */
  body: string

  /** Tags */
  tags: Array<
    | 'performance'
    | 'web'
    | 'http2'
    | 'preload'
    | 'service worker'
    | 'prefetch'
    | 'npm'
    | 'node'
    | 'modules'
    | 'programming'
    | 'caveat'
    | 'yarn'
    | 'package manager'
    | 'module resolution'
    | 'funny'
    | 'javascript'
    | 'typescript'
    | 'bundler'
    | 'graphql'
    | 'ssg'
    | 'blog'
    | 'next.js'
    | 'gatsby'
    | 'Contentful'
  >

  /** Next */
  next?: BlogPost | undefined

  /** Previous */
  previous?: BlogPost | undefined
}

/** A entry of this type stands for a blog post hosted at blog.mudit.xyz */

export interface BlogPost extends Entry<BlogPostFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'blogPost'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}
